-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 01:00:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `todo` ;

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8 ;
USE `todo` ;

-- -----------------------------------------------------
-- Table `todo`.`List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`List` ;

CREATE TABLE IF NOT EXISTS `todo`.`List` (
  `idList` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `hash` VARCHAR(16) NOT NULL,
  `isFavourite` TINYINT NOT NULL DEFAULT 0,
  `mode` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idList`),
  INDEX `fk_List_Users1_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_List_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `todo`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`ListItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`ListItem` ;

CREATE TABLE IF NOT EXISTS `todo`.`ListItem` (
  `idListItem` INT NOT NULL AUTO_INCREMENT,
  `idList` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL DEFAULT 'item',
  `IsDone` TINYINT NOT NULL DEFAULT 0,
  `Description` MEDIUMTEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idListItem`),
  INDEX `fk_ListItem_List_idx` (`idList` ASC) VISIBLE,
  CONSTRAINT `fk_ListItem_List`
    FOREIGN KEY (`idList`)
    REFERENCES `todo`.`List` (`idList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`Users` ;

CREATE TABLE IF NOT EXISTS `todo`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `Surname` VARCHAR(64) NOT NULL,
  `ProfilePicture` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
